name = "package-tracker"
compatibility_date = "2024-04-01"
main = "src/index.js"

[[d1_databases]]
binding = "DB"
database_name = "package-tracker-db"
database_id = "5e734fad-97e9-4723-a62c-e08c77268df7"
